### ISSUE TITLE
Relocating

### ISSUE THREAD

**Issue by HakkaTjakka** [OpenCubicChunks/CubicChunksConverter#6]
The relocating as mentioned did not work.
Specifying the relocatingConfig.txt with 'move all by 0 16 0' when converting the second 'floor'.

But i found another way.

First i convert the second floor that goes from 256 to 512. Anvil -> Cubic Chunks Default option selected in the menu. Not using the 'move all by 0 16 0' or whatever.
Then i convert the created word to a new world with the Cubic Chunks -> Cubic Chunks (Relocating). Using the 'move all by 0 16 0' in relocatingConfig.txt. In the new create world (second) its moves 16 chunks up. (256 blocks). So, ok.

THEN i take the floor 0 region file, and convert it into the second created world.
THEN they are merged.

Maybe there are other ways, but like mentioned before just overwrites the whole 0-255 range, and doesn't moves anything 16 chunks (256 blocks) up..... I assume its only when option Cubic Chunks -> Cubic Chunks (Relocating) option is selected.

Anyway. Its working....

**Comment by Niko-sk2x** [comment]
This is the way you were supposed to do it, more or less. I probably should have explained it better.

**Comment by HakkaTjakka** [comment]
Thanks.

**Comment by HakkaTjakka** [comment]
https://youtu.be/MY9EL2yRO0E
It Worked.

Op vr 9 okt. 2020 om 00:56 schreef Bartosz Skrzypczak <
notifications@github.com>:
