### ISSUE TITLE
Command line options with --headless

### ISSUE THREAD

**Issue by HakkaTjakka** [OpenCubicChunks/CubicChunksConverter#7]
How to use the command line options with --headless parameter?
java -jar cubicchunksconverter-1.75.0-SNAPSHOT-all.jar --headless ???

**Comment by NotStirred** [comment]
I will be rewriting the headless format at some point as the amount of quotes needed for it to work is ridiculous.
Here is an example (please note, the type of quote matters, so just copy and paste the command):
`java -jar cubicchunksconverter-1.75.0-SNAPSHOT-all.jar --headless -- 'srcWorld "./New World"' 'dstWorld "./New WorldCC"' "inFormat Anvil" "outFormat CubicChunks"`

**Comment by HakkaTjakka** [comment]
Thanks. I would never figured that out from the code...
I changed the quotes ' & " on the first two option parameters. Could be a dos cmd thing maybe...

java -jar cubicchunksconverter-1.75.0-SNAPSHOT-all.jar --headless -- "srcWorld './New World'" "dstWorld './New WorldCC'" "inFormat Anvil" "outFormat CubicChunks"

It works.
Perfect.

**Comment by HakkaTjakka** [comment]
https://youtu.be/MY9EL2yRO0E
It Worked.

Op za 10 okt. 2020 om 09:22 schreef Tom Martin <notifications@github.com>:

**Comment by NotStirred** [comment]
Fantastic! Looks amazing!
